[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name   tail
    Path   /fluent-bit/logs/app.log
    Parser java_multiline
    Tag    java.log
    DB     /fluent-bit/tail-db.db
    Refresh_Interval 2
    Read_From_Head  true

[OUTPUT]
    Name        kafka
    Match       java.log
    Brokers     broker:29092
    Topics      java-logs
    Retry_Limit False
